name: 'Terraform_dashboard_destroy'

on:
  workflow_dispatch

jobs:
  tfdestroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
     

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init -reconfigure

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      id : plan
      run: terraform plan -input=false
      
    - name: Terraform destroy
      id: destroy
      if: steps.plan.outcome != 'failure'
      run: terraform destroy -auto-approve
